include: package:lint/analysis_options.yaml

analyzer:
  strong-mode:
    implicit-casts: false
    implicit-dynamic: false
  errors:
    missing_required_param: warning
    missing_return: warning
    todo: ignore
  exclude:
    - lib/generated_plugin_registrant.dart

linter:
  rules:
    - prefer_expression_function_bodies # consider
